# 1. Projenin teknik ismini belirler
spring.application.name=library-management-system-390

# 2. VERITABANI BAGLANTI AYARLARI (Datasource)
spring.datasource.url=jdbc:postgresql://localhost:5432/library_management_application
spring.datasource.username=techpro390
spring.datasource.password=password

# 3. JPA / HIBERNATE AYARLARI
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# 4. HATA YONETIMI
server.error.include-binding-errors=always
server.error.include-message=always
server.error.include-stacktrace=never